FROM node:16-alpine
WORKDIR /usr/local/apps/frontend

COPY package.json ./
RUN npm install && npm cache clean --force
ENV PATH=/usr/local/apps/frontend/node_modules/.bin:$PATH

WORKDIR /usr/local/apps/frontend/dev
COPY tsconfig.json ./
COPY next.config.js ./

COPY styles/ ./styles/
COPY public/ ./public/
COPY pages/  ./pages/
COPY utils/ ./utils/
#COPY .env ./

EXPOSE ${FE_PORT}

CMD ["npm", "run", "dev"]